version: "3.8"
services:
  aws:
    image: localstack/localstack:stable
    container_name: aws
    ports:
      - "127.0.0.1:4566:4566"            # AWS LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - ./var/aws:/var/lib/localstack
      # Exposes the host docker daemon to the container so we can invoke
      # docker api/client from our container
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: local-stack-network
