version: "3.8"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
networks:
  default:
    name: local-stack-network